### ISSUE TITLE
Discussion Questions #1 on Goldstone, Introduction 

### ISSUE THREAD

**Issue by drherr** [drherr/HIST0501-MODERNLATINAMERICA#1]
Please post two discussion questions on today's reading and respond to two different students' questions. In your response, be sure to @ the person whose question you're answering.

**Comment by RJP43** [comment]
**Sample questions:**

1. What is a revolution?  
2. Where is Latin America?

**Comment by drherr** [comment]
**Sample response:**
@RJP43 A revolution is very complicated affair.

**Comment by rushin-spy** [comment]
1. What was your overall reaction to reading the quote from _The Lament of Ipuwer_ at the top of the reading?

2. This reading discusses the many causes and paths a revolution can take. How has reading this introduction affected your views on how revolutions tend to occur?

@alsoarushin-spy  1) I believe that nationalism, in most cases, is one of the driving forces behind revolutions and how they begin. In many revolutions, the ringleaders believe that those in positions of power are ruining their country in some way or have no right to rule the country in the first place, failing to achieve the greatness they know they can reach as per nationalistic leanings.

@samanthakoury 1) One of the many reasons that the beginnings of revolutions are so hard to predict is because it is hard to pinpoint when those willing to risk revolutions reach their breaking point and finally decide that they have had enough. In the case of the American Revolution, tensions were growing for years before the war finally broke out and, had the events at Lexington and Concord not sparked the war, it could have taken many more years for the people of the Colonies to finally say they have had enough. In short, it is nearly impossible to accurately predict human nature, especially when it involves someone's breaking point.

**Comment by cjh115** [comment]
1. Is the "Natural History of Revolutions" accurate with the example revolutions listed or other historical revolutions?

2. Do you believe that revolutions can succeed without support of a foreign nation or superpower?

@tylerdascenzo 2 -  Not necessarily as not every country experiences a revolution. I agree with the text that only certain conditions can exist before a revolution occurs, such as those in the British colonies or the Russian Empire, and that without those conditions a revolution either isn't necessary or possible.

@Ace-Trainer 2 - I think there are cases of the radicals winning, such as the Russian Revolution. Lenin and the Bolsheviks were very much radicals compared to less extreme groups like the Tsarists or Republicans and ended up creating the Soviet Union as a result.

**Comment by samanthakoury** [comment]
1. What do you think is the reason for why we cannot predict just about when a revolution will occur, yet we have all of this research and patterns for when they do happen? 
 2. Since there is so much history with the revolutionaries becoming conflicted afterwards, why do you think the most recent revolutionaries haven't solved that problem yet?  
  

  @rushin-spy 1- When I first read that initial quote I immediately thought of fictional worlds like ones we have in books or on TV today, such as The Walking Dead. Not saying that The Walking Dead was a revolution like the one's that have occurred. However, it is a society with no real laws anymore, common people having control over issues big or small, etc.  It's something crazy to picture, but revolutions are a very real thing that happen.  
@cjh115 2- With the little knowledge I have on revolutions at this moment, I would say that they could very well succeed without support of a foreign nation or superpower. If enough people in that specific nation demand changes, changes will occur with or without outside help. Rulers of a nation can only do so much before it becomes too much.

**Comment by alsoarushin-spy** [comment]
1. To what extent do you think nationalism is important to sparking revolutionary fervor? 

2. Can you think of a situation that would prevent an oppressed people from rising up in rebellion? 

@tylerdascenzo 1- I think the end of a revolution is indicated by a return to stability and the finalization of a "new" order.  Whether it is actually new or merely the original governing system with a new coat of paint is irrelevant, so long as the people involved think there has been a change.

@jpmcl23 2- Negative opinion on a subject has never stopped it from becoming popular, and nationalism is no exception.  There absolutely could be a revolution aided by nationalism that could succeed, as A) not every society currently has a negative view of nationalism and B) in those who do all it needs to do is pitch itself as an explanation for why things are not going the way people want them to obtain sympathy.

**Comment by tylerdascenzo** [comment]
1. What signifies the end of a revolution?  
  
2. Do you think a revolution is a “growing pain” that happens in most young countries trying to evolve?

@jpmcl23 (1) I think each soldier is different in each revolution.  In a revolution involving violence, they should consider the change that might occur.  Do they want change? Will their family be affected, or other personal interests? Those questions could weigh heavily in a soldiers mind. 

@Kylie-D (1) I think a revolution is natural in nature. In other words they aren’t premeditated.  Also after discussing how uncommon revolutions are, it’s still difficult to identify when one could possibly occur.

**Comment by Ace-Trainer** [comment]
@alsoarushin-spy (2) In a situation in which those who are oppressed do not have the necessary supplies or power to rise up this would be a barrier that would most likely prevent them from rebelling. More on this, it would be hard for them to rise up if they did not have access to weapons, if they did not have the ability to make sure every could be fed, if they could not find somewhere to gather and keep there supplies, among other things would hinder a rebellion and make people hesitant. Another factor that might stop people is how the opposition reacts to rebellion, and if they use fear tactics and/or they threaten them with violence and death this can make them fearful to stand-up. So it comes down to these things, but also I think it might come down to the people and whether or not they have the will to fight as it can be easy to succumb to bad conditions.

**Comment by Ace-Trainer** [comment]
@cjh115 (2) I think that it might be possible. The chances are not necessarily high, but it could happen. It comes down to the situation though, for example if the other side has support from outside forces it may not be possible, but if the rebellion can get access to the necessary supplies, and they can get enough people on there side its possible. That being said, there are other factors at play. The opposing side being the government, it has more access to what is needed, and there is the military to take into account which has trained soldiers versus civilians (most likely), so the rebellion will most likely be at a disadvantage, unless they are able to convince the army to be on their side.

**Comment by Ace-Trainer** [comment]
1. What do you think about the theories of revolutions that on the structure, culture, politics, etc. of a country versus the theories that focused political violence?

2. Do you think there ever could have been an outcome in which the radicals won instead? How do you think this would have changed the country?

**Comment by jpmcl23** [comment]
1. At what point does the personal beliefs of soldiers in the army out-weigh their loyalty to the government?  
  
2. Given the views on Nationalism in today's society, do you think a revolution could be successfully accomplished?  
  
@tylerdascenzo yes, i would say that in most younger/newer nations a revolution that occurs would be considered a "growing pain" because it would essentially be the nation going through a power struggle in a more "hands on" way than what we're used to in America. We can go through our changes in power through elections whereas other countries may not have such an easy way to accomplish this, thus, requiring a "revolution".  
  
@Ace-Trainer I would say that The American Revolution would have been a revolution in which the radicals won. Given the time period, the things and ideas that were fought for were completely different views than what people of the time were used to seeing. I think it all depends on what point of view you look at it.

**Comment by jonhoranic** [comment]
1. I am rather surprised that the Introduction did not provide a definition for the type of "revolution" Goldstone wishes to discuss! While we will addressing our own definitions later in class, after this reading what would you think Goldstone would define a "revolution" as?

2. Continuing off ideas of definitions, I have a monkey-wrench to through into the ring. Consider the "Industrial Revolution" and try to pair it with what Goldstone has written in this Introduction. Do you think these theories apply?

@alsoarushin-spy Q2: I have two, both coming straight out of literature. 1. Orwell _1984_ - Suspend peoples' rights to speak or even think through hyper-surveillance, propaganda, and torture. Have an extremely regimented political and social structure built out of a contradictory and amorphous ideology. 2. Huxley _Brave New World_ - Distract the people through choice paralysis by giving them open rights to be as hedonistic and crazy as they want. When people are given everything they "think" they want, they will not be aware of what the larger government structure is doing behind the scenes.

@jpmcl23 Q2: Yes, and disturbingly so. On the "Nationalistic scale" it could tip over to a Populist majority fed by mustache-twirling benefactors or tip toward a large set of individuals (in a singular spread out group or multiple aligned groups) opposed to growing Nationalism openly retaliating to defend what has been reached so far. In both cases, they would need to be properly motivated, have the materials and/or fund, and use a shared set of ideological goals to rally behind. With the proliferation of Internet based communications and spread of information (or misinformation) I would assume that once a catalyst is provided (a singular large event or a set of smaller related ones) it will be extremely difficult for the existing structure and/or the party of opposition would have much power to stop it without outside help.

**Comment by Kylie-D** [comment]
1. Since there are ways to tell when and why a revolution will occur, why isn't there anything done about it?
2. Based off of my first question do many people disagree on the reasons believed to start a revolution and is that why revolutions are reoccurring?

**Comment by era46** [comment]
1.	Compared to other revolutions in human history, why do you think the French Revolution had such a huge impact on human history and why?
2.	How do you think the French Revolution affected the Russian Revolution, if they were at least 100 years apart and do you believe the Russian Revolution would have happened still if the French Revolution would have never happened in the first place and why?

@mattnowakowski Q2- It is hard to say for sure whether or not the Russian Revolution would have occured without the French Revolution due to the influence the French Revolution had on Karl Marx.  Karl Marx was the major influence on the Russian Revolution.  The Russian Revolution was the French Revolution on steroids, for lack of a better term.  Personally, I believe the Russian Revolution would have still happened but it probably would have been a little later on.

**Comment by era46** [comment]
tylerdascenzo (1) To me was signifies the end of a revolution is when people have stopped fighting 100% and their is a new leader that has replaced the old leader and old government.

**Comment by era46** [comment]
alsoarushin-spy (1) I believe that nationalism is a very important element towards sparking revolutionary fever because if you have no pride in your country or government then how can you revolt to replace the government to make your nation better?

**Comment by Kylie-D** [comment]
@alsoarushin-spy (1.) I think that nationalism has to pretty important to sparking revolutionary fervor. I think this because people have to have a reason to go fight and they have to believe in something. So, I really think that nationalism has a lot to do with this subject.

**Comment by Kylie-D** [comment]
@cjh115 (2.) I do believe that revolutions can occur without support of another nation or superpowers. I think this way because if the revolution is powerful enough then they really don't need any other type of support than their own. I'm sure it would help to have support from other stronger nations or superpowers, but I don't think it is necessary.

**Comment by mattnowakowski** [comment]
1.  Has every Revolution since the American Revolution been inspired by the American Revolution?

2.  What is the earliest known large scale Revolution?

**Comment by chrisdutrow** [comment]
1. What would cause the elites to abandon the state?

2. Could a state completely do away with all technical forms of the "elites" if so what could be some consequences.

@cjh115 (2.) Yes. If one were to look at other revolutions like the October Revolution in Russia it is easy to see that certainly does not need outside help to be successful. The people in the revolution are the most important part of the movement. Ideas and the will to change can overcome a lot. Even during the Russian Civil war the western backed White Russian faction was defeated by the unrecognized Reds simply because the reds were united in agenda and rallied much of the public for support.

@rushin-spy (2.) I've learned that there is a lot on the line if a revolution occurs. So this will make many groups of people wish to protect or create their entitled or expected claims. The reading has also showed me that many  sides will work with whoever they believe is in their favor to gain or maintain their personal status quo. This was previously overlooked and allows for an interesting outlook on why some people support certain sides during the revolutionary process.

**Comment by charlesmensa** [comment]
1. Among the three views of how revolutions arise in "Theories of Revolution: The Basic Problems", which do you feel is the most likely to start a revolution?
2. According to Davies, people are more willing to accept oppression if they expect oppression to be a natural part of their society. Do you think that this is the reason that some countries treat their people badly and without the fear of a possible rebellion happening?

**Comment by charlesmensa** [comment]
@mattnowakowski (1.) I think that a statement was made after the colonies were able to win the American Revolution; that anything is possible. I do not think that the probability of the colonies' success in winning a war against an established superpower, like Great Britain, was high at all. As a result, I think that there is a chance that revolutions and revolts were inspired by the American Revolution. An example of that would be how the South considered the Civil War as an extension of the American Revolution, as they were fighting for independence themselves. Their revolt failed, but there was some inspiration from the American Revolution.

**Comment by charlesmensa** [comment]
@chrisdutrow (1.) The elites would be willing to abandon the state if they feel like they should be treated better by the state. The psychological approach to understanding revolutions helps me understand this. If things have been done to improve society, like economic growth, the people of society would feel an amount of resentment towards the state because they have not been treated well previously. The elites of society would be the first to notice that, and thus would be the first of society to abandon the state.

**Comment by arb205** [comment]
1. What are the specifics that make a revolution a "revolution"?
2. What makes a movement, not a rebellion, then after that how does it become a revolution?

**Comment by drherr** [comment]
arb please tell me who you are.
Thanks
Best,
Dr. Herr

**Comment by drherr** [comment]
arb205 who are you?
Best,
Dr. Herr

**Comment by era46** [comment]
1) Between peasant revolts and urban uprisings, which of the two popular uprisings would have more of an impact on actually starting a revolution and why?
2) Why are revolutions not common in the would and why do you think that?

**Comment by drherr** [comment]
This Discussion Question thread is now officially closed.
