### ISSUE TITLE
@era46-Questions

### ISSUE THREAD

**Issue by era46** [drherr/HIST0501-MODERNLATINAMERICA#11]
1. According to the readings, compared to other revolutions in human history, why do you think the French Revolution has such a huge impact on human history and why?

2. How do you think the French Revolution affected the Russian Revolution, if they were at least 100 years apart and do you believe  the Russian Revolution would have happened still if the French Revolution would have never happened in the first place and why?

**Comment by RJP43** [comment]
Hey @era46 I am Rebecca Parker and I am assisting @drherr with implementing this interface in her classroom. NOTICE how we have a discussion thread started [here](https://github.com/drherr/HIST0501-MODERNLATINAMERICA/issues) for each of the 10 wiki/discussion assignments. That means you will not need to create your own wiki page or new issue because we have set up all of the assignments' wiki pages and discussion threads in advance.  
  
Please add your discussion questions to the appropriate discussion thread for this week's assignment - #1   
  
@drherr and I will remove the excess Wiki page you created. Going forward please read our instructions in the [README.md](https://github.com/drherr/HIST0501-MODERNLATINAMERICA/blob/master/README.md) and our [home wiki page](https://github.com/drherr/HIST0501-MODERNLATINAMERICA/wiki) carefully and be sure to reach out to @drherr and/or me (@RJP43) if anything seems unclear. Happy GitHubbing! 💻😁

**Comment by RJP43** [comment]
Whoops @era46, I see now you did figure it out and have already added your discussion questions to the correct thread. Huzzah! Well done!
