### ISSUE TITLE
@era46

### ISSUE THREAD

**Issue by era46** [drherr/HIST0501-MODERNLATINAMERICA#12]
1) Between Peasant revolts and Urban uprisings, which of the two popular uprisings have more of an impact on actually starting a revolution and why?
2)Why are revolutions common in the world and why do you think that?

**Comment by RJP43** [comment]
Hey @era46, once again, I am Rebecca Parker and I am assisting @drherr with implementing this interface in her classroom. **NOTICE** how we have a discussion thread started [here](https://github.com/drherr/HIST0501-MODERNLATINAMERICA/issues) for each of the 10 wiki/discussion assignments. That means you **DO NOT** need to create your own wiki page or your own new issue because we have set up all of the assignments' wiki pages and discussion threads in advance.

Please add your discussion questions to the appropriate discussion thread for this week's assignment - #2 

Going forward please read our instructions in the [README.md](https://github.com/drherr/HIST0501-MODERNLATINAMERICA/blob/master/README.md) and our [home wiki page](https://github.com/drherr/HIST0501-MODERNLATINAMERICA/wiki) carefully and be sure to reach out to @drherr and/or me (@RJP43) if anything seems unclear. Happy GitHubbing! 💻😁

**Comment by RJP43** [comment]
@era46 If you have questions feel free to @ me here in the comments and I will be more than happy to help you!
